Using Tensorflow

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding # type: ignore

# Sample data
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
y = np.array([0, 1, 0, 1])

# Create RNN model
model = Sequential([
    Embedding(input_dim=12, output_dim=8, input_length=3),
    SimpleRNN(4),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fit the model
model.fit(X, y, epochs=10)

# Predict
y_pred = model.predict(X)
print(y_pred)


Epoch 1/10


/Users/siddharthadatta/Library/CloudStorage/OneDrive-Personal/My Repo/.venv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 996ms/step - accuracy: 0.2500 - loss: 0.7204
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2500 - loss: 0.7164
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.2500 - loss: 0.7125
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2500 - loss: 0.7087
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2500 - loss: 0.7049
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5000 - loss: 0.7011
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.6973
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.6936
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.6899
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6862
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
[[0.50813663]
 [0.5116022 ]
 [0.48732635]
 [0.50561553]]


Using Pytorch

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define RNN model using PyTorch
class SimpleRNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleRNN, self).__init__()
        self.embedding = nn.Embedding(12, 8)
        self.rnn = nn.RNN(8, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, x):
        x = self.embedding(x)
        x, _ = self.rnn(x)
        x = self.fc(x[:, -1, :])
        return x

# Convert NumPy arrays to PyTorch tensors
X_tensor = torch.LongTensor(X)
y_tensor = torch.FloatTensor(y.reshape(-1, 1))

# Create the model
model = SimpleRNN(input_dim=3, hidden_dim=4, output_dim=1)

# Define loss and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(10):
    # Forward pass
    outputs = model(X_tensor)
    
    # Compute loss
    loss = criterion(outputs, y_tensor)
    
    # Zero gradients, backward pass, and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f'Epoch [{epoch + 1}/10], Loss: {loss.item():.4f}')


# Predict
with torch.no_grad():
    outputs = model(X_tensor)
    # y_pred_pytorch = (torch.sigmoid(outputs) > 0.5).int().numpy().flatten()
    y_pred_pytorch = (torch.sigmoid(outputs))
    print(y_pred_pytorch)


Epoch [1/10], Loss: 0.6151
Epoch [2/10], Loss: 0.5714
Epoch [3/10], Loss: 0.5308
Epoch [4/10], Loss: 0.4935
Epoch [5/10], Loss: 0.4595
Epoch [6/10], Loss: 0.4288
Epoch [7/10], Loss: 0.4011
Epoch [8/10], Loss: 0.3762
Epoch [9/10], Loss: 0.3538
Epoch [10/10], Loss: 0.3335
tensor([[0.2036],
        [0.6235],
        [0.1876],
        [0.7034]])


In [10]:
X_tensor

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])